#include <boost/test/unit_test.hpp>

#include <string>

#include <boost/asio.hpp>

#include "mqtt/mqtt_client.h"
#include "options/options_mqtt_options.h"
#include "support/unit_test_mqtt_support.h"

using namespace AqualinkAutomate;

namespace
{
	Options::Mqtt::MqttSettings MakeClientTestSettings()
	{
		return Test::MakeMqttSettings();
	}
}

//=============================================================================
// MqttClient construction tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Construction)

BOOST_AUTO_TEST_CASE(Test_Construction_Succeeds)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();

	BOOST_CHECK_NO_THROW(Mqtt::MqttClient client(ioc, settings));
}

BOOST_AUTO_TEST_CASE(Test_Construction_InitialStateDisconnected)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(static_cast<int>(client.GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Disconnected));
}

BOOST_AUTO_TEST_CASE(Test_Construction_NotConnected)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK(!client.IsConnected());
}

BOOST_AUTO_TEST_CASE(Test_Construction_NotRunning)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK(!client.IsRunning());
}

BOOST_AUTO_TEST_CASE(Test_Construction_UsesProvidedClientId)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "my-test-client";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.ClientId(), "my-test-client");
}

BOOST_AUTO_TEST_CASE(Test_Construction_AutoGeneratesClientId)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "";
	Mqtt::MqttClient client(ioc, settings);

	auto client_id = client.ClientId();
	BOOST_CHECK(!client_id.empty());
	BOOST_CHECK_MESSAGE(client_id.find("aqualink-") == 0,
		"Auto-generated client ID should start with 'aqualink-': " + client_id);
}

BOOST_AUTO_TEST_CASE(Test_Construction_AutoGeneratedClientIdsAreUnique)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "";

	Mqtt::MqttClient client1(ioc, settings);
	Mqtt::MqttClient client2(ioc, settings);

	auto id1 = client1.ClientId();
	auto id2 = client2.ClientId();

	BOOST_CHECK_NE(id1, id2);
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient lifecycle tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Lifecycle)

BOOST_AUTO_TEST_CASE(Test_Start_SetsRunningState)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();

	BOOST_CHECK(client->IsRunning());
	BOOST_CHECK(!client->IsConnected()); // Not yet connected, just started
	BOOST_CHECK_EQUAL(static_cast<int>(client->GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Connecting));

	client->Stop();
}

BOOST_AUTO_TEST_CASE(Test_Start_TwiceIsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();
	BOOST_CHECK_NO_THROW(client->Start()); // Should not throw
	BOOST_CHECK(client->IsRunning());

	client->Stop();
}

BOOST_AUTO_TEST_CASE(Test_Stop_ClearsState)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();
	client->Publish("test/topic", "payload");
	client->Stop();

	BOOST_CHECK(!client->IsRunning());
	BOOST_CHECK(!client->IsConnected());
	BOOST_CHECK_EQUAL(static_cast<int>(client->GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Disconnected));

	// Publish queue should be cleared on stop
	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_CHECK(queue.empty());
}

BOOST_AUTO_TEST_CASE(Test_Stop_WhenNotRunningIsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_NO_THROW(client.Stop());
	BOOST_CHECK(!client.IsRunning());
}

BOOST_AUTO_TEST_CASE(Test_Stop_EmitsDisconnectedSignal)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	std::string disconnect_reason;
	client->OnDisconnected.connect([&disconnect_reason](const std::string& reason) {
		disconnect_reason = reason;
	});

	client->Start();
	client->Stop();

	BOOST_CHECK(!disconnect_reason.empty());
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient topic building tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Topics)

BOOST_AUTO_TEST_CASE(Test_TopicPrefix_ReturnsConfiguredPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "mypool";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.TopicPrefix(), "mypool");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_WithPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "test";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("status/pool"), "test/status/pool");
	BOOST_CHECK_EQUAL(client.BuildTopic("command/device"), "test/command/device");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_EmptyPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("status/pool"), "status/pool");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_ComplexSubtopic)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "home/pool";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("ha/pump_filter"), "home/pool/ha/pump_filter");
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient publish queue tests (drop-oldest, FIFO, retain preserved)
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_PublishQueue)

BOOST_AUTO_TEST_CASE(Test_Publish_QueuesToDeque)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Publish("topic/a", "payload_a");
	client->Publish("topic/b", "payload_b");
	client->Publish("topic/c", "payload_c");

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_REQUIRE_EQUAL(queue.size(), 3);

	// Verify FIFO ordering
	BOOST_CHECK_EQUAL(queue[0].topic, "topic/a");
	BOOST_CHECK_EQUAL(queue[0].payload, "payload_a");
	BOOST_CHECK_EQUAL(queue[1].topic, "topic/b");
	BOOST_CHECK_EQUAL(queue[2].topic, "topic/c");
}

BOOST_AUTO_TEST_CASE(Test_Publish_RetainFlagPreserved)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Publish("topic/a", "payload_a", false);
	client->Publish("topic/b", "payload_b", true);

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_REQUIRE_EQUAL(queue.size(), 2);
	BOOST_CHECK_EQUAL(queue[0].retain, false);
	BOOST_CHECK_EQUAL(queue[1].retain, true);
}

BOOST_AUTO_TEST_CASE(Test_Publish_QueueOverflow_DropsOldest)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	// Fill queue to capacity (MAX_PUBLISH_QUEUE_SIZE = 1000)
	for (int i = 0; i < 1000; ++i)
	{
		client->Publish("topic/" + std::to_string(i), "payload");
	}

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_CHECK_EQUAL(queue.size(), 1000);
	BOOST_CHECK_EQUAL(queue.front().topic, "topic/0");

	// One more should drop the oldest
	client->Publish("topic/overflow", "overflow_payload");

	BOOST_CHECK_EQUAL(queue.size(), 1000);
	BOOST_CHECK_EQUAL(queue.front().topic, "topic/1"); // topic/0 was dropped
	BOOST_CHECK_EQUAL(queue.back().topic, "topic/overflow");
	BOOST_CHECK_EQUAL(client->DroppedCount(), 1u);
}

BOOST_AUTO_TEST_SUITE_END()
