#include <boost/test/unit_test.hpp>

#include <string>

#include <boost/asio.hpp>

#include "mqtt/mqtt_client.h"
#include "options/options_mqtt_options.h"
#include "support/unit_test_mqtt_support.h"

using namespace AqualinkAutomate;

namespace
{
	Options::Mqtt::MqttSettings MakeClientTestSettings()
	{
		return Test::MakeMqttSettings();
	}
}

//=============================================================================
// MqttClient construction tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Construction)

BOOST_AUTO_TEST_CASE(Test_Construction_Succeeds)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();

	BOOST_CHECK_NO_THROW(Mqtt::MqttClient client(ioc, settings));
}

BOOST_AUTO_TEST_CASE(Test_Construction_InitialStateDisconnected)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(static_cast<int>(client.GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Disconnected));
}

BOOST_AUTO_TEST_CASE(Test_Construction_NotConnected)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK(!client.IsConnected());
}

BOOST_AUTO_TEST_CASE(Test_Construction_NotRunning)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK(!client.IsRunning());
}

BOOST_AUTO_TEST_CASE(Test_Construction_UsesProvidedClientId)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "my-test-client";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.ClientId(), "my-test-client");
}

BOOST_AUTO_TEST_CASE(Test_Construction_AutoGeneratesClientId)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "";
	Mqtt::MqttClient client(ioc, settings);

	auto client_id = client.ClientId();
	BOOST_CHECK(!client_id.empty());
	BOOST_CHECK_MESSAGE(client_id.find("aqualink-") == 0,
		"Auto-generated client ID should start with 'aqualink-': " + client_id);
}

BOOST_AUTO_TEST_CASE(Test_Construction_AutoGeneratedClientIdsAreUnique)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.client_id = "";

	Mqtt::MqttClient client1(ioc, settings);
	Mqtt::MqttClient client2(ioc, settings);

	auto id1 = client1.ClientId();
	auto id2 = client2.ClientId();

	BOOST_CHECK_NE(id1, id2);
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient lifecycle tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Lifecycle)

BOOST_AUTO_TEST_CASE(Test_Start_SetsRunningState)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();

	BOOST_CHECK(client->IsRunning());
	BOOST_CHECK(!client->IsConnected()); // Not yet connected, just started
	BOOST_CHECK_EQUAL(static_cast<int>(client->GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Connecting));

	client->Stop();
}

BOOST_AUTO_TEST_CASE(Test_Start_TwiceIsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();
	BOOST_CHECK_NO_THROW(client->Start()); // Should not throw
	BOOST_CHECK(client->IsRunning());

	client->Stop();
}

BOOST_AUTO_TEST_CASE(Test_Stop_ClearsState)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Start();
	client->Publish("test/topic", "payload");
	client->Stop();

	BOOST_CHECK(!client->IsRunning());
	BOOST_CHECK(!client->IsConnected());
	BOOST_CHECK_EQUAL(static_cast<int>(client->GetState()),
		static_cast<int>(Mqtt::MqttClient::State::Disconnected));

	// Publish queue should be cleared on stop
	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_CHECK(queue.empty());
}

BOOST_AUTO_TEST_CASE(Test_Stop_WhenNotRunningIsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_NO_THROW(client.Stop());
	BOOST_CHECK(!client.IsRunning());
}

BOOST_AUTO_TEST_CASE(Test_Stop_EmitsDisconnectedSignal)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	std::string disconnect_reason;
	client->OnDisconnected.connect([&disconnect_reason](const std::string& reason) {
		disconnect_reason = reason;
	});

	client->Start();
	client->Stop();

	BOOST_CHECK(!disconnect_reason.empty());
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient topic building tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Topics)

BOOST_AUTO_TEST_CASE(Test_TopicPrefix_ReturnsConfiguredPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "mypool";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.TopicPrefix(), "mypool");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_WithPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "test";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("status/pool"), "test/status/pool");
	BOOST_CHECK_EQUAL(client.BuildTopic("command/device"), "test/command/device");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_EmptyPrefix)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("status/pool"), "status/pool");
}

BOOST_AUTO_TEST_CASE(Test_BuildTopic_ComplexSubtopic)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.topic_prefix = "home/pool";
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.BuildTopic("ha/pump_filter"), "home/pool/ha/pump_filter");
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient publish queue tests (drop-oldest, FIFO, retain preserved)
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_PublishQueue)

BOOST_AUTO_TEST_CASE(Test_Publish_QueuesToDeque)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Publish("topic/a", "payload_a");
	client->Publish("topic/b", "payload_b");
	client->Publish("topic/c", "payload_c");

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_REQUIRE_EQUAL(queue.size(), 3);

	// Verify FIFO ordering
	BOOST_CHECK_EQUAL(queue[0].topic, "topic/a");
	BOOST_CHECK_EQUAL(queue[0].payload, "payload_a");
	BOOST_CHECK_EQUAL(queue[1].topic, "topic/b");
	BOOST_CHECK_EQUAL(queue[2].topic, "topic/c");
}

BOOST_AUTO_TEST_CASE(Test_Publish_RetainFlagPreserved)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	client->Publish("topic/a", "payload_a", false);
	client->Publish("topic/b", "payload_b", true);

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_REQUIRE_EQUAL(queue.size(), 2);
	BOOST_CHECK_EQUAL(queue[0].retain, false);
	BOOST_CHECK_EQUAL(queue[1].retain, true);
}

BOOST_AUTO_TEST_CASE(Test_Publish_QueueOverflow_DropsOldest)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	// Fill queue to capacity (MAX_PUBLISH_QUEUE_SIZE = 1000)
	for (int i = 0; i < 1000; ++i)
	{
		client->Publish("topic/" + std::to_string(i), "payload");
	}

	auto& queue = Test::MqttClientPacketTest::GetPublishQueue(*client);
	BOOST_CHECK_EQUAL(queue.size(), 1000);
	BOOST_CHECK_EQUAL(queue.front().topic, "topic/0");

	// One more should drop the oldest
	client->Publish("topic/overflow", "overflow_payload");

	BOOST_CHECK_EQUAL(queue.size(), 1000);
	BOOST_CHECK_EQUAL(queue.front().topic, "topic/1"); // topic/0 was dropped
	BOOST_CHECK_EQUAL(queue.back().topic, "topic/overflow");
	BOOST_CHECK_EQUAL(client->DroppedCount(), 1u);
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient last-will (LWT) tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Will)

BOOST_AUTO_TEST_CASE(Test_GetWill_DefaultsToEmpty)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK(!client.GetWill().has_value());
}

BOOST_AUTO_TEST_CASE(Test_SetWill_StoresConfiguration)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	client.SetWill("status/availability", "offline", true);

	const auto& will = client.GetWill();
	BOOST_REQUIRE(will.has_value());
	BOOST_CHECK_EQUAL(will->topic, "status/availability");
	BOOST_CHECK_EQUAL(will->payload, "offline");
	BOOST_CHECK_EQUAL(will->retain, true);
}

BOOST_AUTO_TEST_CASE(Test_SetWill_RetainDefaultsTrue)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	client.SetWill("status/availability", "offline");

	const auto& will = client.GetWill();
	BOOST_REQUIRE(will.has_value());
	BOOST_CHECK_EQUAL(will->retain, true);
}

BOOST_AUTO_TEST_CASE(Test_SetWill_RetainCanBeDisabled)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	client.SetWill("status/availability", "offline", false);

	const auto& will = client.GetWill();
	BOOST_REQUIRE(will.has_value());
	BOOST_CHECK_EQUAL(will->retain, false);
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient client-id generation tests
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_GenerateClientId)

BOOST_AUTO_TEST_CASE(Test_GenerateClientId_FormatContract)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	auto id = Test::MqttClientPacketTest::CallGenerateClientId(client);

	// "aqualink-" (9 chars) + 8 random hex chars.
	BOOST_REQUIRE_EQUAL(id.size(), 17u);
	BOOST_CHECK(id.starts_with("aqualink-"));

	const auto suffix = id.substr(9);
	BOOST_CHECK_EQUAL(suffix.size(), 8u);
	for (char c : suffix)
	{
		BOOST_CHECK_MESSAGE(std::string("0123456789abcdef").find(c) != std::string::npos,
			std::string("client-id suffix must be lowercase hex, saw: ") + c);
	}
}

BOOST_AUTO_TEST_CASE(Test_GenerateClientId_ProducesDistinctValues)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	auto id1 = Test::MqttClientPacketTest::CallGenerateClientId(client);
	auto id2 = Test::MqttClientPacketTest::CallGenerateClientId(client);

	BOOST_CHECK_NE(id1, id2);
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient reconnect-backoff tests (exponential growth, cap, saturation,
// jitter bounds). delay_pre_jitter = base * 2^min(attempts, 10), capped at max;
// jitter is added uniformly from [0, delay_pre_jitter / 4].
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_ReconnectDelay)

namespace
{
	Options::Mqtt::MqttSettings MakeBackoffSettings(std::chrono::seconds initial, std::chrono::seconds max)
	{
		auto settings = Test::MakeMqttSettings();
		settings.reconnect_delay_initial = initial;
		settings.reconnect_delay_max = max;
		return settings;
	}
}

BOOST_AUTO_TEST_CASE(Test_ReconnectDelay_FirstAttemptIsBaseDelay)
{
	boost::asio::io_context ioc;
	// base = 4s, attempts = 0 -> pre-jitter = 4, jitter in [0, 1].
	Mqtt::MqttClient client(ioc, MakeBackoffSettings(std::chrono::seconds(4), std::chrono::seconds(3600)));
	Test::MqttClientPacketTest::SetReconnectAttempts(client, 0);

	auto delay = Test::MqttClientPacketTest::CallCalculateReconnectDelay(client).count();
	BOOST_CHECK_GE(delay, 4);
	BOOST_CHECK_LE(delay, 5);
}

BOOST_AUTO_TEST_CASE(Test_ReconnectDelay_GrowsExponentially)
{
	boost::asio::io_context ioc;
	// base = 4s: attempt n -> pre-jitter = 4 * 2^n, jitter in [0, (4*2^n)/4].
	Mqtt::MqttClient client(ioc, MakeBackoffSettings(std::chrono::seconds(4), std::chrono::seconds(100000)));

	for (std::uint16_t n = 0; n <= 4; ++n)
	{
		Test::MqttClientPacketTest::SetReconnectAttempts(client, n);
		const std::int64_t pre_jitter = static_cast<std::int64_t>(4) << n;
		auto delay = Test::MqttClientPacketTest::CallCalculateReconnectDelay(client).count();
		BOOST_CHECK_GE(delay, pre_jitter);
		BOOST_CHECK_LE(delay, pre_jitter + pre_jitter / 4);
	}
}

BOOST_AUTO_TEST_CASE(Test_ReconnectDelay_CappedAtMaxDelay)
{
	boost::asio::io_context ioc;
	// base = 10s, max = 20s. attempt 5 -> pre-jitter = 10 * 32 = 320, capped to 20,
	// jitter in [0, 5] -> result in [20, 25].
	Mqtt::MqttClient client(ioc, MakeBackoffSettings(std::chrono::seconds(10), std::chrono::seconds(20)));
	Test::MqttClientPacketTest::SetReconnectAttempts(client, 5);

	auto delay = Test::MqttClientPacketTest::CallCalculateReconnectDelay(client).count();
	BOOST_CHECK_GE(delay, 20);
	BOOST_CHECK_LE(delay, 25);
}

BOOST_AUTO_TEST_CASE(Test_ReconnectDelay_SaturatesAtTenShifts)
{
	boost::asio::io_context ioc;
	// base = 1s, huge cap. The shift is clamped at min(attempts, 10), so attempt 10,
	// 11 and 50 all share pre-jitter = 1 * 2^10 = 1024 and jitter in [0, 256].
	Mqtt::MqttClient client(ioc, MakeBackoffSettings(std::chrono::seconds(1), std::chrono::seconds(1000000)));

	const std::int64_t pre_jitter = static_cast<std::int64_t>(1) << 10; // 1024

	for (std::uint16_t n : { std::uint16_t{ 10 }, std::uint16_t{ 11 }, std::uint16_t{ 50 } })
	{
		Test::MqttClientPacketTest::SetReconnectAttempts(client, n);
		auto delay = Test::MqttClientPacketTest::CallCalculateReconnectDelay(client).count();
		BOOST_CHECK_GE(delay, pre_jitter);
		BOOST_CHECK_LE(delay, pre_jitter + pre_jitter / 4);
	}
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient subscribe / poll guard tests (synchronous early-return paths)
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Guards)

BOOST_AUTO_TEST_CASE(Test_Subscribe_WhenNotConnected_IsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	// Not connected: Subscribe() must log a warning and return without touching
	// the endpoint (which is not started) — i.e. no throw, no state change.
	BOOST_REQUIRE(!client->IsConnected());
	BOOST_CHECK_NO_THROW(client->Subscribe("some/topic", 1));
	BOOST_CHECK(!client->IsConnected());
}

BOOST_AUTO_TEST_CASE(Test_Poll_WhenNotRunning_IsHarmless)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	// Not running: Poll() takes the early-return branch before any flush work.
	BOOST_REQUIRE(!client->IsRunning());
	BOOST_CHECK_NO_THROW(client->Poll());
}

BOOST_AUTO_TEST_CASE(Test_Poll_WhenConnected_FlushesWithoutThrowing)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	// Force the connected/running state so Poll() runs the flush path
	// (FlushIfConnected) rather than the early-return guard.
	Test::MqttClientPacketTest::ForceConnectedState(*client);
	client->Publish("topic/a", "payload_a");

	BOOST_REQUIRE(client->IsRunning());
	BOOST_CHECK_NO_THROW(client->Poll());
}

BOOST_AUTO_TEST_SUITE_END()

//=============================================================================
// MqttClient diagnostics-accessor tests (initial values)
//=============================================================================

BOOST_AUTO_TEST_SUITE(TestSuite_MqttClient_Diagnostics)

BOOST_AUTO_TEST_CASE(Test_Diagnostics_InitialCounters)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.PublishQueueDepth(), 0u);
	BOOST_CHECK_EQUAL(client.ReconnectAttempts(), 0u);
	BOOST_CHECK_EQUAL(client.PublishedCount(), 0u);
	BOOST_CHECK_EQUAL(client.DroppedCount(), 0u);
	BOOST_CHECK(client.LastError().empty());
}

BOOST_AUTO_TEST_CASE(Test_Diagnostics_SettingsAccessorReflectsConfig)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	settings.broker_host = "broker.example";
	settings.broker_port = 8883;
	Mqtt::MqttClient client(ioc, settings);

	BOOST_CHECK_EQUAL(client.Settings().broker_host, "broker.example");
	BOOST_CHECK_EQUAL(client.Settings().broker_port, 8883);
}

BOOST_AUTO_TEST_CASE(Test_Diagnostics_PublishQueueDepthTracksPublishes)
{
	boost::asio::io_context ioc;
	auto settings = MakeClientTestSettings();
	auto client = std::make_shared<Mqtt::MqttClient>(ioc, settings);

	BOOST_CHECK_EQUAL(client->PublishQueueDepth(), 0u);
	client->Publish("topic/a", "a");
	client->Publish("topic/b", "b");
	BOOST_CHECK_EQUAL(client->PublishQueueDepth(), 2u);
}

BOOST_AUTO_TEST_SUITE_END()
