name: CMake

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          BUILD_PRESET: linux-x64-release-clang
        - os: windows-latest
          BUILD_PRESET: windows-x64-release-msvc

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/cache@v3
      with :
        path: |
            ${{github.workspace}}/deps/vcpkg/buildtrees
            ${{github.workspace}}/deps/vcpkg/downloads
            ${{github.workspace}}/deps/vcpkg/packages
        key: ${{ runner.os }}-build-${{ matrix.BUILD_PRESET }}-${{ hashFiles('vcpkg.json') }}

    - uses: ashutoshvarma/setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt dist-upgrade -y
        sudo apt install -y build-essential cmake curl git ninja-build pkg-config wget unzip zip
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy main'
        sudo apt update
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build --preset ${{matrix.BUILD_PRESET}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --test-dir ${{github.workspace}}/build/test --output-on-failure
